name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
    - title: 'Features'
      labels:
          - 'feature'
          - 'enhancement'
    - title: 'Bug Fixes'
      labels:
          - 'fix'
          - 'bugfix'
          - 'bug'
    - title: 'Refactoring'
      labels:
          - 'refactor'
    - title: 'test'
      labels:
          - 'test'
exclude-labels:
    - 'deploy'
    - 'exclude'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
    major:
        labels:
            - 'major'
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    ## What's Changed
    $CHANGES
