name: AI Code Reviewer

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
permissions: write-all
jobs:
  chatgpt-code-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Review
        uses: magnificode-ltd/chatgpt-code-reviewer@v0.0.8
        with:
        model: gpt-4o
        # max_tokens: 4096
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}